from django import forms
from .models import *


class ConfigurationForm(forms.ModelForm,forms.Form):
    class Meta:
        model = configurations
        fields = "__all__"
        widgets = {
            'minimum_monthly_purchase_to_become_active': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'associate_advisor_accumulated_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'associate_advisor_percent': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control percentage'}),
            'advisor_accumulated_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'advisor_percent': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control percentage'}),
            'associate_manager_accumulated_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'associate_manager_percent': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control percentage'}),
            'manager_accumulated_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'manager_percent': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control percentage'}),
            'associate_director_accumulated_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'associate_director_percent': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control percentage'}),
            'associate_director_ppv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'associate_director_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'associate_director_legs': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'bronze_director_ppv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'bronze_director_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'bronze_director_legs': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'silver_director_ppv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'silver_director_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'silver_director_legs': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'gold_director_ppv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'gold_director_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'gold_director_legs': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'platinum_director_ppv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'platinum_director_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'platinum_director_legs': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'titanium_director_ppv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'titanium_director_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'titanium_director_legs': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'sapphire_director_ppv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'sapphire_director_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'sapphire_director_legs': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'emerald_director_ppv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'emerald_director_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'emerald_director_legs': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'jade_director_ppv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'jade_director_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'jade_director_legs': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'crown_director_ppv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'crown_director_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'crown_director_legs': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'diamond_director_ppv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'diamond_director_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'diamond_director_legs': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'black_diamond_director_ppv': forms.TextInput(attrs={'placeholder': 'Enter Accumulated PGPV', 'class': 'form-control accumulated_pgpv'}),
            'black_diamond_director_pgpv': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'black_diamond_director_legs': forms.TextInput(attrs={'placeholder': 'Enter Percent', 'class': 'form-control accumulated_pgpv'}),
            'perform_roll_up': forms.Select(choices=choice,attrs={'class': 'form-control'}),
            'perform_dynamic_compression_actives': forms.Select(choices=choice,attrs={'class': 'form-control'}),
            'perform_dynamic_compression_directors': forms.Select(choices=choice,attrs={ 'class': 'form-control'}),
        }

class super_modelForm(forms.ModelForm,forms.Form):
    class Meta:
        model = super_model
        fields = "__all__"
        widgets = {
            'purchase_pv': forms.TextInput(attrs={'placeholder': 'type here....', 'class': 'form-control percentage'}),
            'direct_bonus_bv': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'direct_bonus_capping': forms.TextInput(attrs={'placeholder': 'type here..', 'class': 'form-control percentage'}),
            'team_building_bonus_capping': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'team_building_bonus_minimum_ppv': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'level_1st_downline': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'level_2nd_downline': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'level_3rd_downline': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'level_4th_downline': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'level_5th_downline': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'life_style_fund_tbb': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
        }
class infinity_modelForm(forms.ModelForm,forms.Form):
    class Meta:
        model = infinity_model
        fields = "__all__"
        widgets = {
            'show_to_advisor': forms.Select(choices=infinity_choice,attrs={'class': 'form-control'}),
            'associate_advisor_percent': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'advisor_percent': forms.TextInput(attrs={'placeholder': 'type here..', 'class': 'form-control percentage'}),
            'associate_manager_percent': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'manager_percent': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'associate_director_above_percent': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'calculate_differential_bonus' : forms.Select(choices=differential_bonus,attrs={'class': 'form-control'}),
            'advisor_pv': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'director_pv': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'how_many_advisor_select': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'how_much_pv_give': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'how_many_point_per_self_pgbv_allocate': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'black_diamond_direct_circle': forms.Select(choices=circle,attrs={'class': 'form-control'}),
            'black_diamond_percentage_personal_bonus_downline_on_which_nurturing_bonus_paid': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'diamond_direct_circle': forms.Select(choices=circle,attrs={'class': 'form-control'}),
            'diamond_percentage_personal_bonus_downline_on_which_nurturing_bonus_paid': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'crown_direct_circle': forms.Select(choices=circle,attrs={'class': 'form-control'}),
            'crown_percentage_personal_bonus_downline_on_which_nurturing_bonus_paid': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'jade_direct_circle': forms.Select(choices=circle,attrs={'class': 'form-control'}),
            'jade_percentage_personal_bonus_downline_on_which_nurturing_bonus_paid': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'emerald_direct_circle': forms.Select(choices=circle,attrs={'class': 'form-control'}),
            'emerald_percentage_personal_bonus_downline_on_which_nurturing_bonus_paid': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'sapphire_direct_circle': forms.Select(choices=circle,attrs={'class': 'form-control'}),
            'sapphire_percentage_personal_bonus_downline_on_which_nurturing_bonus_paid': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'titanium_direct_circle': forms.Select(choices=circle,attrs={'class': 'form-control'}),
            'titanium_percentage_personal_bonus_downline_on_which_nurturing_bonus_paid': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'platinum_direct_circle': forms.Select(choices=circle,attrs={'class': 'form-control'}),
            'platinum_percentage_personal_bonus_downline_on_which_nurturing_bonus_paid': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'gold_direct_circle': forms.Select(choices=circle,attrs={'class': 'form-control'}),
            'gold_percentage_personal_bonus_downline_on_which_nurturing_bonus_paid': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'silver_direct_circle': forms.Select(choices=circle,attrs={'class': 'form-control'}),
            'silver_percentage_personal_bonus_downline_on_which_nurturing_bonus_paid': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'bronze_direct_circle': forms.Select(choices=circle,attrs={'class': 'form-control'}),
            'bronze_percentage_personal_bonus_downline_on_which_nurturing_bonus_paid': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'associate_direct_circle': forms.Select(choices=circle,attrs={'class': 'form-control'}),
            'associate_percentage_personal_bonus_downline_on_which_nurturing_bonus_paid': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'black_diamond_direct_self': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'black_diamond_direct_1': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'black_diamond_direct_2': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'black_diamond_direct_3': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'black_diamond_direct_4': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'black_diamond_direct_5': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'black_diamond_direct_6': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'black_diamond_direct_7': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'black_diamond_direct_8': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'black_diamond_direct_9': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'black_diamond_direct_10': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'diamond_direct_self': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'diamond_direct_1': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'diamond_direct_2': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'diamond_direct_3': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'diamond_direct_4': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'diamond_direct_5': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'diamond_direct_6': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'diamond_direct_7': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'diamond_direct_8': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'diamond_direct_9': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'diamond_direct_10': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'crown_direct_self': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'crown_direct_1': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'crown_direct_2': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'crown_direct_3': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'crown_direct_4': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'crown_direct_5': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'crown_direct_6': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'crown_direct_7': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'crown_direct_8': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'crown_direct_9': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'crown_direct_10': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'jade_direct_self': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'jade_direct_1': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'jade_direct_2': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'jade_direct_3': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'jade_direct_4': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'jade_direct_5': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'jade_direct_6': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'jade_direct_7': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'jade_direct_8': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'jade_direct_9': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'jade_direct_10': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'emerald_direct_self': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'emerald_direct_1': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'emerald_direct_2': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'emerald_direct_3': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'emerald_direct_4': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'emerald_direct_5': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'emerald_direct_6': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'emerald_direct_7': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'emerald_direct_8': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'emerald_direct_9': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'emerald_direct_10': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'sapphire_direct_self': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'sapphire_direct_1': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'sapphire_direct_2': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'sapphire_direct_3': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'sapphire_direct_4': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'sapphire_direct_5': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'sapphire_direct_6': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'sapphire_direct_7': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'sapphire_direct_8': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'sapphire_direct_9': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'sapphire_direct_10': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'titanium_direct_self': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'titanium_direct_1': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'titanium_direct_2': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'titanium_direct_3': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'titanium_direct_4': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'titanium_direct_5': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'titanium_direct_6': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'titanium_direct_7': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'titanium_direct_8': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'titanium_direct_9': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'titanium_direct_10': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'platinum_direct_self': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'platinum_direct_1': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'platinum_direct_2': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'platinum_direct_3': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'platinum_direct_4': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'platinum_direct_5': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'platinum_direct_6': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'platinum_direct_7': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'platinum_direct_8': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'platinum_direct_9': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'platinum_direct_10': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'gold_direct_self': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'gold_direct_1': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'gold_direct_2': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'gold_direct_3': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'gold_direct_4': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'gold_direct_5': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'gold_direct_6': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'gold_direct_7': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'gold_direct_8': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'gold_direct_9': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'gold_direct_10': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'silver_direct_self': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'silver_direct_1': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'silver_direct_2': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'silver_direct_3': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'silver_direct_4': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'silver_direct_5': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'silver_direct_6': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'silver_direct_7': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'silver_direct_8': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'silver_direct_9': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'silver_direct_10': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'bronze_direct_self': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'bronze_direct_1': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'bronze_direct_2': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'bronze_direct_3': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'bronze_direct_4': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'bronze_direct_5': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'bronze_direct_6': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'bronze_direct_7': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'bronze_direct_8': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'bronze_direct_9': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'bronze_direct_10': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'associate_direct_self': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'associate_direct_1': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'associate_direct_2': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'associate_direct_3': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'associate_direct_4': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'associate_direct_5': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'associate_direct_6': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'associate_direct_7': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'associate_direct_8': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'associate_direct_9': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'associate_direct_10': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'vacation_fund_qualified_direct_level':  forms.Select(choices=qualification,attrs={'class': 'form-control'}),
            'vacation_fund_percentage_pb_sb_nb_bmb': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'vehicle_fund_qualified_direct_level':  forms.Select(choices=qualification,attrs={'class': 'form-control'}),
            'vehicle_fund_percentage_pb_sb_nb_bmb': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'shelter_fund_qualified_direct_level':  forms.Select(choices=qualification,attrs={'class': 'form-control'}),
            'shelter_fund_percentage_pb_sb_nb_bmb': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'consistent_retailers_enabled_income':  forms.Select(choices=qualification,attrs={'class': 'form-control'}),
            'minimum_purchase_in_earning_month': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'minimum_purchase_in_redeeming_month': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
            'cap_on_maximum_purchase': forms.TextInput(attrs={'placeholder': 'type here...', 'class': 'form-control percentage'}),
        }