from django.urls import path

from . import views, views_wa

urlpatterns = [
    path('', views.home, name="mlm_admin"),
    path('category-list', views.category_list, name="category-list"),
    path('add_category', views.add_category, name="add_category"),
    path('edit_category/<int:myid>', views.edit_category, name="edit_category"),
    path('view_category/<int:myid>', views.view_category, name="view_category"),
    path('delete_category/<int:myid>', views.delete_category, name="delete_category"),
    path('add_product', views.add_product, name="add_product"),
    path('product-list', views.product_list, name="product-list"),
    path('edit_product/<int:myid>', views.edit_product, name="edit_product"),
    path('copy_product/<int:myid>', views.copy_product, name="copy_product"),
    path('view_product/<int:myid>', views.view_product, name="view_product"),
    path('delete_product/<int:myid>', views.delete_product, name="delete_product"),
    path('order-list', views.order_list, name="order-list"),
    path('group-order-list', views.group_order_list, name="group-order-list"),
    path('allorder-list', views.allorder, name="allorder-list"),
    path('accepted_order', views.accepted_order, name="accepted_order"),
    path('accept_order/<int:myid>', views.accept_order, name="accept_order"),
    path('accept_order_dv/<int:myid>', views.accept_order_dv, name="accept_order_dv"),
    path('accept_order_pkr/<int:myid>', views.accept_order_pkr, name="accept_order_pkr"),
    path('sheet_config', views.SheetConfigView, name="sheet_config"),
    path('send_to_sheet/<int:myid>', views.send_to_sheet, name='send_to_sheet'),
    path('status_ready_to_dispatch/<int:myid>', views.status_ready_to_dispatch),
    path('status_dispatched/<int:myid>', views.status_dispatched),
    path('status_delivered/<int:myid>', views.status_delivered),
    path('status_reject/<int:myid>', views.status_reject),
    path('status_refund/<int:myid>', views.status_refund),
    path('status_returned/<int:myid>', views.status_returned),
    path('ready_to_dispatch', views.ready_to_dispatch, name="ready_to_dispatch"),
    path('dispatched', views.dispatched, name="dispatched"),
    path('delivered', views.delivered, name="delivered"),
    path('reject_order', views.reject_order, name="reject_order"),
    path('refund', views.refund, name="refund"),
    path('decline_order', views.decline_order, name="decline_order"),
    path('returned', views.returned, name="returned"),

    #c&f view for mlm_admin
    path('cf_order-list', views.cf_order_list, name="cf_order-list"),
    path('cf_allorder-list', views.cf_allorder, name="cf_allorder-list"),
    path('cf_accepted_order', views.cf_accepted_order, name="cf_accepted_order"),
    path('cf_ready_to_dispatch', views.cf_ready_to_dispatch, name="cf_ready_to_dispatch"),
    path('cf_dispatched', views.cf_dispatched, name="cf_dispatched"),
    path('cf_delivered', views.cf_delivered, name="cf_delivered"),
    path('cf_reject_order', views.cf_reject_order, name="cf_reject_order"),
    path('cf_refund', views.cf_refund, name="cf_refund"),
    path('cf_decline_order', views.cf_decline_order, name="cf_decline_order"),
    path('cf_returned', views.cf_returned, name="cf_returned"),

    path('orderstatus/<int:myid>', views.orderstatus, name="orderstatus"),
    path('change_mc_status/<int:myid>_mc', views.change_mc_status, name="change_mc_status"),
    path('delete-order/<int:myid>/<str:check>', views.delete_order, name="delete-order"),
    path('view_order/<int:myid>', views.view_order, name="view_order"),
    path('add_batch', views.add_batch, name="add_batch"),
    path('batch_list', views.batch_list, name="batch_list"),
    path('delete_batch/<int:myid>', views.delete_batch, name="delete_batch"),
    path('edit_batch/<int:myid>', views.edit_batch, name="edit_batch"),
    path('copy_batch/<int:myid>', views.copy_batch, name="copy_batch"),
    path('view_batch/<int:myid>', views.view_batch, name="view_batch"),
    path('add_material', views.add_material, name="add_material"),
    path('material_list', views.material_list, name="material_list"),
    path('material_state_list', views.material_state_assignment_list_list, name="material_state_list"),
    path('material_center_wise_sale', views.material_center_wise_sale, name="material_center_wise_sale"),
    path('delete_material/<int:myid>', views.delete_material, name="delete_material"),
    path('edit_material/<int:myid>', views.edit_material, name="edit_material"),
    path('view_material/<int:myid>', views.view_material, name="view_material"),
    path('material_reff', views.validate_ref, name="material_reff"),
    path('add_banner', views.add_banner, name="add_banner"),
    path('banner-list', views.banner_list, name="banner-list"),
    path('edit_banner/<int:myid>', views.edit_banner, name="edit_banner"),
    path('view_banner/<int:myid>', views.view_banner, name="view_banner"),
    path('add_referral', views.add_referral, name="add_referral"),
    path('referral_list', views.referral_list, name="referral_list"),
    path('view_referral/<int:myid>', views.view_referral, name="view_referral"),
    path('generat_referral/<int:myid>', views.generat_referral, name="generat_referral"),
    #path('user_list', views.userlist, name="user_list"),
    path('add_purchase', views.add_purchase, name="add_purchase"),
    path('add_column', views.add_column, name="add_column"),
    path('edit_column', views.edit_column, name="edit_column"),
    path('purchase_list', views.purchase_list, name="purchase_list"),
    path('edit_purchase/<int:myid>', views.edit_purchase, name="edit_purchase"),
    path('delete_purchase/<int:myid>', views.delete_purchase, name="delete_purchase"),
    path('view_purchase/<int:myid>', views.view_purchase, name="view_purchase"),
    path('add_sale', views.add_sale, name="add_sale"),
    path('add_sale_cnf', views.add_sale_cnf, name="add_sale_cnf"),
    path('add_loyalty_sale', views.add_loyalty_sale, name="add_loyalty_sale"),
    path('add_saleField', views.add_saleField, name="add_saleField"),
    path('edit_saleField', views.edit_saleField, name="edit_saleField"),
    path('check_f', views.check_f, name="check_f"),
    path('sale_list', views.sale_list, name="sale_list"),
    path('cf_sale_list', views.cf_sale_list, name="cf_sale_list"),
    path('edit_sale/<int:myid>', views.edit_sale, name="edit_sale"),
    path('delete_sale/<int:myid>', views.delete_sale, name="delete_sale"),
    path('view_sale/<int:myid>', views.view_sale, name="view_sale"),
    path('batch_price', views.batch_price, name="batch_price"),
    path('product_detail', views.product_detail, name="product_detail"),
    path('batch_field', views.batch_field, name="batch_field"),
    path('editbatch_field', views.editbatch_field, name="editbatch_field"),
    path('purchase_detail_field', views.purchase_product_detail, name="purchase_detail_field"),
    path('inventory_details', views.inventory_details, name="inventory_details"),
    path('blanceDetails_list', views.blanceDetails, name="blanceDetails_list"),
    path('Details_list', views.details, name="Details_list"),
    path('inventory', views.inventory, name="inventory"),
    path('edit_user/<int:myid>', views.registration_edit_user, name="edit_user"),
    path('login', views.loginAdmin, name="mlm_admin_login"),
    path('rebuildingCron', views.rebuilding_cron, name="mlm_admin_rebuildingCron"),
    path('d_rebuildingCron', views.D_rebuilding_cron, name="mlm_admin_d_rebuildingCron"),
    path('recalculate_distributor_orders', views.recalculate_distributor_orders, name="recalculate_distributor_orders"),
    path('remove_unlinked_product_batch', views.remove_unlinked_product_batch, name="remove_unlinked_product_batch"),
    path('shiping_charge', views.Add_shiping_config, name="mlm_admin_shiping_charge"),
    path('pending_sale', views.pending_sale, name="mlm_admin_pending_sale"),
    path('export_excel/<int:myid>', views.export_excel, name="mlm_admin_export_excel"),
    path('sendemail', views.sendemail, name="sendemail"),
    path('distributor_list', views.distributor_list, name="mlm_admin_distributor_list"),
    path('everdistributor_list', views.everdistributor_list, name="mlm_admin_ever_distributor_list"),
    path('make_distributor/<int:myid>', views.make_distributor, name="mlm_admin_make_distributor"),
    path('remove_distributor/<int:myid>', views.remove_distributor, name="mlm_admin_remove_distributor"),
    path('current_distributor/', views.current_distributor, name="mlm_admin_current_distributor"),
    path('current_distributor_cri/', views.current_distributor_cri, name="mlm_admin_current_distributor_cri"),
    # cnf
    path('cnf_list', views.cnf_list, name="mlm_admin_cnf_list"),
    path('make_cnf/<int:myid>', views.make_cnf, name="mlm_admin_make_cnf"),
    path('remove_cnf/<int:myid>', views.remove_cnf, name="mlm_admin_remove_cnf"),
    path('current_cnf/', views.current_cnf, name="mlm_admin_current_cnf"),
    path('evercnf_list', views.evercnf_list, name="mlm_admin_ever_cnf_list"),
    path('add_user_permission', views.add_user_permission, name="mlm_admin_add_user_permission"),
    path('user_permission_list', views.user_permission_list, name="mlm_admin_user_permission_list"),
    path('view_user_permission/<int:myid>', views.view_user_permission, name="mlm_admin_view_user_permission"),
    path('edit_user_permission/<int:myid>', views.edit_user_permission, name="mlm_admin_edit_user_permission"),
    path('distributor_inventory_details', views.distributor_inventory_details, name="distributor_inventory_details"),
    path('ajax_material_center', views.ajax_material_center, name='ajax_material_center'),
    path('download_sale', views.sale_downlaod, name='mlm_admin_download_sale'),
    path('download_order', views.order_downlaod, name='mlm_admin_download_order'),
    path('download_purchase', views.purchase_downlaod, name='mlm_admin_download_purchase'),
    # path('variant_field',views.variant_field,name='mlm_admin_variant_field'),
    path('material_name/', views.mc_name, name='material_name'),
    path('distributors_sale_list', views.distributors_sale_list, name='mlm_admin_distributors_sale_list'),
    path('distributor_view_sale<int:myid>', views.distributor_view_sale, name="mlm_admin_distributor_view_sale"),
    path('distributor_edit_sale/<int:myid>', views.distributors_edit_sale, name="mlm_admin_distributor_edit_sale"),
    path('distributor_delete_sale/<int:myid>', views.distributor_delete_sale, name="mlm_admin_distributor_delete_sale"),
    path('distributor_invoice/<int:myid>', views.invoice_check, name="mlm_admin_distributor_invoice"),
    path('track_order/<int:myid>', views.track_order, name="mlm_track_order"),
    path('pv_bv_rebuilding', views.pv_bv_rebuilding, name="pv_bv_rebuilding"),
    path('manual_verification/', views.manual_verification, name="manual_verification"),
    path('manual_verification/verify/<int:myid>', views.mv_details, name="mv_details"),
    path('wallet_configuration/', views.wallet_cofiguration_list, name="wallet_configuration"),
    path('wallet/details/<int:myid>', views.wc_details, name="wallet_details"),
    path('wallet/details/edit/<int:myid>', views.wallet_detail_edit, name="wallet_detail_edit"),
    path('wallet/transaction-history/<int:myid>', views.wallet_transaction, name="wallet_transaction"),
    path('user-activity-log/', views.useractivity_log, name="useractivity_log"),
    path('user-activity-log/details/<int:myid>', views.Useractivity_detail, name="useractivity_detail"),
    path('cache-clear', views.Clear_cache, name="cache_clear"),
    path('users-kyc-status-verified', views.kyc_user_screen_verified, name="users-kyc-status-verified"),
    path('users-kyc-status-manual', views.kyc_user_screen_manual, name="users-kyc-status-manual"),
    path('users-kyc-status-unverified', views.kyc_user_screen_unverified, name="users-kyc-status-unverified"),
    path('auto-kyc-verification/<int:mid>', views.auto_kyc_verification, name="auto_kyc_verification"),

    ######  template related urls ###########
    path('template-list', views.TemplateListView.as_view(), name='template_list'),
    path('template-add', views.TemplateCreateView.as_view(), name='template_add'),
    path('template-update/<int:pk>', views.TemplateUpdateView.as_view(), name='template_update'),
    path('template-delete/<int:pk>', views.TemplateDeleteView.as_view(), name='template_delete'),
    path('template-view/<int:pk>', views.TemplateDetailView.as_view(), name='template_view'),
    ######  template related urls end ###########
    path('change_mobile_number/<int:myid>', views.change_mobile_number, name="change_mobile_number"),
    path('change_email_id/<int:myid>', views.change_email_id, name="change_email_id"),
    path('email_sanitation_check', views.email_sanitation_check, name="email_sanitation_check"),
    # Payment Gateway
    path('add_gateway', views.GatewayAddUpdateView.as_view(), name="add_gateway"),
    path('priority_gateway', views.PriorityGatewayAddUpdateView.as_view(),
                                                    name="priority_gateway"),
    path('priority_gateway/<int:pk>', views.PriorityGatewayAddUpdateView.as_view(),
                                                         name="update_priority_gateway"),
    path('add_gateway/<int:pk>', views.GatewayAddUpdateView.as_view(), name="update_gateway"),
    path('gateway_list', views.GatewayNameListView.as_view(), name='list_gateway'),
    path('priority_list', views.GatewayPriorityListView.as_view(), name='list_priority'),
    path('gateway_delete/<int:myid>', views.delete_gateway, name='gateway_delete'),
    path('delete_priority/<int:myid>', views.delete_priority, name="delete_priority"),
    path('blocked_user_list', views.BlockedUserListView.as_view(), name='blocked_user_list'),
    path('address_list/', views.address_list, name='address_list'),
    path('address_add/', views.address_add, name='address_add'),
    path('address_edit/<int:myid>', views.address_edit, name='address_edit'),
    path('address_view/<int:myid>', views.address_view, name='address_view'),
    path('tds_calculation/', views.tds_calculation, name='tds_calculation'),

    # For Whatsapp Greetings
    path('add_greeting', views_wa.add_greeting, name='add_greeting'),
    path('list_greetings', views_wa.list_greetings, name='list_greetings'),
    path('edit_greeting/<int:greeting_id>', views_wa.edit_greeting, name='edit_greeting'),
    path('delete_greeting/<int:greeting_id>', views_wa.delete_greeting, name='delete_greeting'),
    path('preview_greeting/<int:greeting_id>', views_wa.preview_greeting, name="preview_greeting"),
    path('preview_greeting/<int:greeting_id>/<int:user_id>', views_wa.preview_greeting, name="preview_greeting"),
    path('send_mock_greeting/<int:greeting_id>', views_wa.send_mock_wa_messages, name="send_mock_wa"),
    path('send_wa_messages/<int:greeting_id>', views_wa.send_wa_messages, name="send_wa_messages"),
    path('send_wa_messages/<int:greeting_id>/<int:user_group>', views_wa.send_wa_messages, name="send_wa_messages"),
    path('send_todays_greetings', views_wa.send_todays_greetings, name="send_todays_greetings"),

    path('send_bulk_messages', views_wa.send_bulk_messages, name='send_bulk_messages'),
    path('whatsapp_configuration', views_wa.whatsapp_configuration, name='whatsapp_configuration')

]
