
"""
Django settings for portal_auretics_com project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# from decouple import config, Csv

# import environ
# # Initialise environment variables
# env = environ.Env()
# environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5r1-b@0zlt@66i=pcfukun5q++b5$%e%1=^sz))i452_kc54a+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ['shivameknous.pythonanywhere.com','*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'accounts',
    'shop',
    'mlm_admin',
    'multiselectfield',
    'distributor',
    'mlm_calculation',
    'business',
    'notify',
    'audit',
    'realtime_calculation',
    # 'realtime_calculation_v2',
    'django.contrib.humanize',
    'import_export',
    'loadtest',
    'c_and_f',
    'wallet',
    'mis_reports',
    # 'payu_biz',
    # 'paywix'
    'activitylog.apps.ActivitylogConfig',
    'slick_reporting',
    'crispy_forms',
    'ckeditor',
    'ckeditor_uploader',
    'payment_gateway',
    'crm',
    'pyjama',
]



CRONJOBS = [
    ('01 0 * * *', 'shop.cron.cron_run'),
    ('01 0 * * *', 'mlm_admin.cron_jobs.update_inventry'),
    ('01 0 * * *', 'distributor.cron.cron_run'),
    ('01 0 * * *', 'realtime_calculation.views.total_pv_bv_cron'),
    ('05 0 * * *', 'mlm_calculation.pgpv_pgbv.do_pgpv_pgbv_calculation'),
]

CRON_CLASSES = [
    "mlm_calculation.cron_jobs.PgpvPgbvDailyUpdate",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# login With mail id
AUTHENTICATION_BACKENDS = (
    'accounts.backend.EmailAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
)

ROOT_URLCONF = 'portal_auretics_com.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.extras',
                'shop.context_processors.cart_item_count',
                'shop.context_processors.cart_distributor_checkout',
                'shop.context_processors.wallet_setup',
                # 'django.core.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'portal_auretics_com.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql_psycopg2', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
#             'NAME': 'portal_auretics_com_db_8',                      # Or path to database file if using sqlite3.
#             # The following settings are not used with sqlite3:
#             'USER': 'postgres_one',
#             'PASSWORD': 'SUaQHcbC8g7X',
#             'HOST': 'localhost',                      # Empty for localhost through domain sockets or           '13.235.17.143' for localhost through TCP.
#         }
#     }
# }


#################################################

# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql_psycopg2', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
#             'NAME': 'portal_auretics_com-db-nar-1',                      # Or path to database file if using sqlite3.
#             # The following settings are not used with sqlite3:
#             'USER': 'postgres',
#             'PASSWORD': 'SUaQHcbC8g7X',
#             'HOST': '3.109.73.211',                      # Empty for localhost through domain sockets or           '13.235.17.143' for localhost through TCP.
#         }
#     }




#################################################
# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql_psycopg2', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
#             'NAME': 'portal_auretics_com-db-18',                      # Or path to database file if using sqlite3.
#             # The following settings are not used with sqlite3:
#             'USER': 'postgres',
#             'PASSWORD': 'SUaQHcbC8g7X',
#             'HOST': '3.109.73.211',                      # Empty for localhost through domain sockets or           '13.235.17.143' for localhost through TCP.
#         }
#     }


# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql_psycopg2', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
#             'NAME': 'portal_auretics_com-db-sat-10',                      # Or path to database file if using sqlite3.
#             # The following settings are not used with sqlite3:
#             'USER': 'postgres',
#             'PASSWORD': 'SUaQHcbC8g7X',
#             'HOST': '3.109.73.211',                      # Empty for localhost through domain sockets or           '13.235.17.143' for localhost through TCP.
#         }
#     }


# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql_psycopg2', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
#             'NAME': 'portal_auretics_com-db-36',                      # Or path to database file if using sqlite3.
#             # The following settings are not used with sqlite3:
#             'USER': 'postgres',
#             'PASSWORD': 'website',
#             'HOST': 'localhost',                      # Empty for localhost through domain sockets or           '13.235.17.143' for localhost through TCP.
#         }
#     }
DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
            # 'NAME': 'portal_auretics_com-db-56',                # Or path to database file if using sqlite3.
            'NAME': 'auretics_clean_2',  # Or path to database file if using sqlite3.
            # 'NAME': 'auretics',
            # The following settings are not used with sqlite3:
            'USER': 'postgres',
            'PASSWORD': 'website',
        }
    }

# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql_psycopg2', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
#             'NAME': 'portal_auretics_com-db-42',                      # Or path to database file if using sqlite3.
#             # The following settings are not used with sqlite3:
#             'USER': 'postgres',
#             'PASSWORD': '123456',
#         }
#     }

# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql_psycopg2', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
#             'NAME': 'portal_auretics_com-db-sat-11',                      # Or path to database file if using sqlite3.
#             # The following settings are not used with sqlite3:
#             'USER': 'postgres',
#             'PASSWORD': 'SUaQHcbC8g7X',
#             'HOST': '3.109.73.211',                      # Empty for localhost through domain sockets or           '13.235.17.143' for localhost through TCP.
#         }
#     }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# static file seting
STATICFILES_DIRS = os.path.join(BASE_DIR, 'static'),
# STATIC_ROOT = '/static'
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
# PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
# STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')

MEDIA_URL = '/media/'
# MEDIA_ROOT = '/home/shivameknous/portal_auretics_com/media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#email setup
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'singhmohit12390@gmail.com'
EMAIL_HOST_PASSWORD = 'tveqqovgldqtsdjb'
EMAIL_USE_TLS = True
 #password associated with above email-id
DATE_INPUT_FORMATS = ('%d/%m/%Y','%d-%m-%Y','%Y-%m-%d')

GOOGLE_RECAPTCHA_SITE_KEY = '6LeVCKgaAAAAAKELQHJMHeWi1g7k592G_xojVRbe' #your reCAPTCHA SITE key

GOOGLE_RECAPTCHA_SECRET_KEY = '6LeVCKgaAAAAADsn51OcTxu6-wZ_THxWCT7b_GoA' #your reCAPTCHA SECRET key

# Paywix config for payu gateway
PAYU_CONFIG = {
    "merchant_key": "7GKgLS",
    "merchant_salt": "RW67aFqS",
    # "merchant_key": "gtKFFx",
    # "merchant_salt": "eCwWELxi",
    # "mode": "test",
    "mode": "live",
    "success_url": "http://127.0.0.1:8000/payu/success",
    "failure_url": "http://127.0.0.1:8000/payment/payu/failure"
}
# ZAAKPAY config for ZAAKPAY gateway

ZAAKPAY_MERCHANT_IDENTIFIER = "e302bc8f451a47498ba0d3e0e95d943b"  # Get your merchant identifier on Zaakpay.com
ZAAKPAY_SECRET_KEY = "0fd92f6b85914a3bb85154f042d6d80e"  # Get your secret key on Zaakpay.com
# Api URL

ENVIRONMENT = "https://api.zaakpay.com"  # For Live transaction use https://api.zaakpay.com

# Payment processing URL's
TRANSACTION_API_URL = "/api/paymentTransact/V8"

# Transaction update URL's
UPDATE_API_URL = "/updatetransaction"

# Transaction check status URL's
TRANSACTION_STATUS_API_URL = "/checkTxn?v=5"

# Url for test response file
RETURN_URL = "http://127.0.0.1:8000/zaakpay_callback/"  # Change this with your response file

SITE_URL= "http://127.0.0.1:8000"

# RAZOR config for RAZOR gateway
RAZOR_KEY_ID = "rzp_live_FoBYFWo05rPt3O"
RAZOR_KEY_SECRET = "9HVvVesHKK7e5L8vA8W0llFe"

CRON_CLASSES = [
    "mlm_calculation.cron_jobs.PgpvPgbvDailyUpdate",
    "mlm_admin.cron_jobs.ChechDeliveryStatus",
]

# Shiprocket API
shiprocket_api_user = "support@auretics.com"
shiprocket_api_pass = 'Auretics@1234'

# AWS API
aws_access_key_id = "AKIA6E7IKIUXGSY2KH5Z"
aws_secret_access_key = "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"
region_name = "ap-south-1"

# Nimbus API
nimbus_username = "t1671910"
nimbus_password = "psfl1015"

#Signzy API
signzy_username = "auretics_prod"
signzy_password = "mBe6tJ4baKQJgNhFk7xB"
signzy_spoc = "arjun@auretics.com"
signzy_callback = "http://portal.auretics.com"

CACHE_TTL = 0
# CACHE_TTL = 60 * 60 * 24 # 1 Day
 

# WALLET = env('WALLET')
# CACHING = env('CACHING')

# [AG] Custom Variables
audit_mode = False
WALLET = "OFF"
CACHING = "ON"
GROUP_CHECKOUT = True

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

 
if not DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379/1',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'TIMEOUT': CACHE_TTL,
        }
    }

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
#     }
# }

try:
    from .local_settings import *
except ImportError:
    pass

CRISPY_TEMPLATE_PACK = 'bootstrap4'

IMPORT_EXPORT_USE_TRANSACTIONS = True
IMPORT_EXPORT_SKIP_ADMIN_LOG = True

SERVER_EMAIL = 'webmaster@auretics.com'
DEFAULT_FROM_EMAIL = 'webmaster@auretics.com'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240 # higher than the count of fields


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'timestamp': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            # 'level': 'ERROR',
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'timestamp'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            # 'level': 'DEBUG',
            'propagate': True,
        },
    },
}

CKEDITOR_CONFIGS = {
    "default": {
        "removePlugins": "stylesheetparser",
    },
    'awesome_ckeditor': {
        'toolbar': 'Basic',
    },
}
CKEDITOR_UPLOAD_PATH = "uploads/"


# Delhivery Details
DL_PROD_MODE = True
if DL_PROD_MODE:
    dl_url = 'https://track.delhivery.com'
    dl_api = '2c44dbf48fb3d17e25b581859239effa3705183c'
    dl_client = 'SF AURETICS 0109941'
else:
    dl_url = 'https://staging-express.delhivery.com'
    dl_api = '9ce46f95a85261017ebe89157ebec86dd56488fa'
    dl_client = 'SFAURETICS0109941-B2C'

pickrr_api = '57b52b88582592770871d33e00f159cd268013'

# Whatsapp Greetings Settings
# (Width, Height)
GREETINGS_SIZE = (1280, 1280)
GREETING_THUMBNAIL_SIZE = (128, 128)

WA_NUMBER = "+14155238886"

# Twilio Tokens
TWILIO_ACCOUNT_SID = 'AC013bdf6649c9837e147fb2e2bce76085'  # os.environ['TWILIO_ACCOUNT_SID']
TWILIO_AUTH_TOKEN = 'a0099944cb8ad0d1ac519197a5625046'  # os.environ['TWILIO_AUTH_TOKEN']

TWILIO_SANDBOX_NUMBER = "whatsapp:+14155238886"

# WATI Tokens
WATI_TOKEN = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJmYzRlZGM2Mi1lYmNiLTQ2MmYtYWM3NS1mNjY2ODdiYTAxMTQiLCJ1bmlxdWVfbmFtZSI6ImJoYXZpbnBhdGVsLndpZnRjYXBAZ21haWwuY29tIiwibmFtZWlkIjoiYmhhdmlucGF0ZWwud2lmdGNhcEBnbWFpbC5jb20iLCJlbWFpbCI6ImJoYXZpbnBhdGVsLndpZnRjYXBAZ21haWwuY29tIiwiYXV0aF90aW1lIjoiMDUvMTcvMjAyMiAxMjowMDozNyIsImRiX25hbWUiOiJ3YXRpX2FwcCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlRSSUFMIiwiZXhwIjoxNjUzNDM2ODAwLCJpc3MiOiJDbGFyZV9BSSIsImF1ZCI6IkNsYXJlX0FJIn0.9K2Ishsc20fCH4lXP9GS6QKUY1U6cnLepNawlsre__g"
WATI_ENDPOINT = r"https://app-server.wati.io"

# WASSEMGER Tokent
WASSENGER_TOKEN = "d8be12620f4d1d9ac31fdee92e92993bdebf1617cdceab11019ea5fe782311aa19048af767c3cec7"
